---
abstract: 'Object Orientated Interface to CloudFlare client API'
author:
  - 'Peter Roberts <me+dev@peter-r.co.uk>'
build_requires:
  File::Spec: '3.40'
  HTTP::Message: '6.00'
  Moose: '1.22'
  Test::Exception: '0.32'
  Test::LWP::UserAgent: '0.002'
  Try::Tiny: '0.11'
  Type::Tiny: 0.039_12
  perl: '5.014'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: CloudFlare-Client
provides:
  CloudFlare::Client:
    file: lib/CloudFlare/Client.pm
    version: 0.03_9
  CloudFlare::Client::Exception::Connection:
    file: lib/CloudFlare/Client/Exception/Connection.pm
    version: 0.03_9
  CloudFlare::Client::Exception::Upstream:
    file: lib/CloudFlare/Client/Exception/Upstream.pm
    version: 0.03_9
  CloudFlare::Client::Types:
    file: lib/CloudFlare/Client/Types.pm
    version: 0.03_9
requires:
  IPC::System::Simple: '1.22'
  JSON::Any: '1.26'
  Kavorka: '0.001'
  LWP::Protocol::https: '6.02'
  LWP::UserAgent: '6.02'
  Modern::Perl: '1.20120105'
  Moo: '0.009005'
  MooX::StrictConstructor: '0.001'
  Moose: '1.22'
  MooseX::StrictConstructor: '0.13'
  Readonly: '1.04'
  Throwable: '0.200003'
  Type::Tiny: 0.039_12
  autodie: '2.11'
  indirect: '0.24'
  namespace::autoclean: '0.12'
  perl: '5.014'
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=CloudFlare-Client
  homepage: https://bitbucket.org/pwr22/ddflare
  repository: git://git@bitbucket.org:pwr22/ddflare.git
version: 0.03_9
