---
abstract: 'Object Orientated Interface to CloudFlare client API'
author:
  - 'Peter Roberts <me+dev@peter-r.co.uk>'
build_requires:
  File::Spec: '3.40'
  HTTP::Response: '6.00'
  LWP::Simple: '6.00'
  Test::Exception: '0.32'
  Test::LWP::UserAgent: '0.002'
  Test::Moose: '1.22'
  Test::TypeTiny: '0.001'
  Try::Tiny: '0.11'
  perl: '5.014'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.140640'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: CloudFlare-Client
provides:
  CloudFlare::Client:
    file: lib/CloudFlare/Client.pm
    version: 0.03_2
  CloudFlare::Client::Exception::Connection:
    file: lib/CloudFlare/Client/Exception/Connection.pm
    version: 0.03_2
  CloudFlare::Client::Exception::Upstream:
    file: lib/CloudFlare/Client/Exception/Upstream.pm
    version: 0.03_2
  CloudFlare::Client::Types:
    file: lib/CloudFlare/Client/Types.pm
    version: 0.03_2
requires:
  IPC::System::Simple: '1.22'
  JSON::Any: '1.26'
  Kavorka: '0.001'
  LWP::Protocol::https: '6.02'
  LWP::UserAgent: '6.02'
  Modern::Perl: '1.20120105'
  Moo: '0.009005'
  MooX::StrictConstructor: '0.001'
  Readonly: '1.04'
  Throwable::Error: '0.200003'
  Type::Library: '0.008'
  Type::Utils: '0.001'
  Types::Standard: '0.001'
  autodie: '2.11'
  namespace::autoclean: '0.12'
  perl: '5.014'
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=CloudFlare-Client
version: 0.03_2
