---
abstract: 'Interface to Cloudflare client API'
author:
  - 'Peter Roberts <me+dev@peter-r.co.uk>'
build_requires:
  Pod::Coverage: 0.18
  Test::CheckManifest: 0.9
  Test::Moose: 2.121
  Test::More: 0.98
  Test::Pod: 1.22
  Test::Pod::Coverage: 1.08
  Test::TypeTiny: 0.044
  Try::Tiny: 0.22
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CloudFlare-Client
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 1.29
  JSON::Any: 1.34
  LWP::UserAgent: 6.06
  Method::Signatures: 20140224
  Modern::Perl: 1.20140107
  Moose: 2.121
  MooseX::StrictConstructor: 0.19
  MooseX::Types: 0.44
  MooseX::Types::Moose: 0.44
  Readonly: 2
  autodie: 2.25
  namespace::autoclean: 0.19
  perl: 0
  strict: 1.07
  warnings: 1.18
version: 0.01
