---
abstract: 'Object Orientated Interface to CloudFlare client API'
author:
  - 'Peter Roberts <me+dev@peter-r.co.uk>'
build_requires:
  File::Spec: '3.40'
  HTTP::Response: '6.00'
  LWP::Simple: '6.00'
  Test::Exception: '0.32'
  Test::LWP::UserAgent: '0.002'
  Test::Moose: '1.22'
  Test::TypeTiny: '0.001'
  Try::Tiny: '0.11'
  perl: '5.014'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.140640'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: CloudFlare-Client
requires:
  Carp: '1.26'
  IPC::System::Simple: '1.22'
  JSON::Any: '1.26'
  LWP::UserAgent: '6.00'
  Method::Signatures: '20110923'
  Modern::Perl: '1.20120105'
  Moose: '1.22'
  MooseX::SemiAffordanceAccessor: '0.09'
  MooseX::StrictConstructor: '0.13'
  MooseX::Types: '0.26'
  Readonly: '1.04'
  Throwable::Error: '0.200003'
  autodie: '2.11'
  namespace::autoclean: '0.12'
  perl: '5.014'
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=CloudFlare-Client
version: 0.03_0
