---
abstract: 'Object Orientated Interface to Cloudflare client API'
author:
  - 'Peter Roberts <me+dev@peter-r.co.uk>'
build_requires:
  File::Spec: '3.40'
  Test::Moose: '2.0402'
  Test::More: '0.99'
  Test::TypeTiny: '0.001'
  Try::Tiny: '0.12'
  perl: '5.016'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141520'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: CloudFlare-Client
requires:
  Carp: '1.24'
  JSON::Any: '1.30'
  LWP::UserAgent: '6.04'
  Method::Signatures: '20111125'
  Modern::Perl: '1.20120105'
  Moose: '2.0402'
  MooseX::StrictConstructor: '0.17'
  MooseX::Types: '0.32'
  Readonly: '1.04'
  Throwable::Error: '0.200003'
  autodie: '2.11'
  namespace::autoclean: '0.14'
  perl: '5.016'
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=CloudFlare-Client
version: '0.02'
